---
title: "R Notebook"
output: html_notebook
---

```{r}

options(scipen = 999)

library(tidyverse)
library(lme4)
library (lmerTest);
library(Rmisc)
library(MuMIn)

#we have 66787 uniqu users 
dh = read_csv ('../data/mean_abs_diff_sim_indiv.csv') %>% 
  select(-...1) %>% 
  select(id=userid, 
         threshold,
         poli=poli_affil,
         abs_dif_empirical=mean_abs_diff_empi,
         abs_dif_random=mean_abs_diff_random) %>% 
  gather(homoph_condition, sim_abs_value, -id, -threshold,-poli) %>% 
  filter(threshold<=5)

da = read_csv ('../data/acrophily_sim_indiv.csv') %>% 
  select(id=userid,
         threshold,
         poli=poli_affil,
         ego_empirical = orig_rating_ego, 
         peer_empirical =orig_rating_peer,
         peer_homoph= homoph_rating_peer,
         peer_acroph= acroph_rating_peer_min,
         peer_comp_acroph = acroph_rating_peer_max) %>% 
  gather(acroph_condition, sim_value, -id, -threshold,-poli, -ego_empirical) %>% 
    filter(threshold<=5)

da$dif = da$sim_value-da$ego_empirical
da$more_extreme = ifelse(da$dif <=0,0,1)

mean(da$more_extreme)

dfc <- summarySE(da, measurevar="more_extreme", groupvars=c("acroph_condition","poli"), na.rm = T)



head(dh)
head(da)

sum(da$threshold)


#function
rsquare = function (reg){
  1-var(residuals(reg))/(var(model.response(model.frame(reg))))
}

logit2prob <- function(logit){
  odds <- exp(logit)
  prob <- odds / (1 + odds)
  return(prob)
}
```



```{r descriptives}

numbers = read_csv ('../data/acrophily_sim_indiv.csv') 

table(numbers$poli_affil)

des = da %>% 
  filter(threshold <6) %>% 
  group_by (id) %>% 
  slice(1) %>% 
  drop_na(id)

table(des$poli_affil)

total = numbers %>% 
  group_by (poli_affil) %>% 
  dplyr::summarise(total= sum(threshold))




dh_des = dh %>% 
  group_by (id) %>% 
  slice(1) #%>% 
  #drop_na(id)









```


```{r politial affiliation }


des %>% 
  mutate(poli_affil = ifelse(poli == 'right', 'Conservatives', 'Liberals')) %>%
  ggplot(aes(x=ego_empirical,  color=poli_affil)) +
  geom_histogram(fill='transparent') +
  facet_wrap(~poli_affil) +
  scale_fill_manual(values = c("blue", "red"))+
  annotate("text", x=0.22, y = -1000, label= "Moderate") + 
  annotate("text", x=1.82, y=-1000, label= "Extreme") + 
  theme_minimal() +
  theme(plot.title = element_text(hjust = 0.5, face="bold", size = 16),
        legend.position = ('none'),
        axis.title.y = element_text(face="bold",  size=14),
        axis.text.x  = element_text( vjust=0.5, size=12),
        axis.text.y  = element_text( vjust=0.5, size=12),
        axis.title.x = element_text( vjust=0.5, size=14),
        strip.text = element_text(size = 14))+
    labs(x='', y='Count',
       title="Users' Political Affiliation")


ggsave('../figures/user_poli_ratings.jpg', width = 9, height = 6)

```



```{r homophily}
dh$homoph_condition = factor(dh$homoph_condition)
dh$homoph_condition_effect = ifelse (dh$homoph_condition=="abs_dif_empirical", -1,1)
dh$poli=factor(dh$poli)
dh$poli_effect = ifelse (dh$poli=="left" , -1,1)
rh = lmer (sim_abs_value ~homoph_condition_effect *
            scale(threshold)*
            poli_effect+
              (1|id), dh);summary(rh)




crh = confint(rh)

r.squaredGLMM(rh)

label_names <- c('right' = 'Conservatives', 'left' = 'Liberals')


dfc <- summarySE(dh, measurevar="sim_abs_value", groupvars=c("homoph_condition", "threshold", "poli"), na.rm = T)

ggplot(dfc,aes(x=threshold, y=sim_abs_value ,fill = homoph_condition, colour =homoph_condition))+
    geom_errorbar(aes(ymin=sim_abs_value-ci, ymax=sim_abs_value+ci), width=.1)+
    geom_line( aes(linetype= homoph_condition, group=homoph_condition),size = .5)+
    geom_point()+
    theme_bw()+
    theme(plot.title = element_text(hjust=0.5,size = rel(1.5)),
          axis.title.y = element_text(face="bold",  size=14),
          axis.text.x  = element_text( vjust=0.5, size=18),
          axis.text.y  = element_text( vjust=0.5, size=12),
          axis.title.x = element_text( vjust=0.5, size=18)) +
    facet_wrap(~poli, labeller=as_labeller(label_names), ncol = 1)+

    labs(title = "title",
          x = "xtitle", 
          y = "ytitle")





abs_diff_plot <- dh %>%
  ggplot(aes(x=threshold, y=sim_abs_value, group=sim_abs_value, color=homoph_condition)) +
  geom_smooth(method = "lm")+
  facet_wrap(~poli, labeller=as_labeller(label_names), ncol = 1)+
  #geom_line()+
  #geom_errorbar(aes(ymin=ci_lower, ymax=ci_upper, color=sim_condition), alpha=0.2)+
  scale_color_manual(labels = c("Empirical", "Random"), values = c("orange", "blue"))+
  labs(x='Retweet Number', y="Mean Absolute Difference", color="Simulation Condition")+
  theme_bw();abs_diff_plot


ggsave('../figures/abs_diff_plot.jpg', width=8, height=7)

abs_diff_plot

```
```{r}
crh
```

```{r}
da$acroph_condition=factor(da$acroph_condition)
da$acroph_condition= relevel (da$acroph_condition, "peer_empirical")
da$acroph_condition_effect = ifelse (da$acroph_condition=="peer_empirical", -1,1)
da$poli=factor(da$poli)
da$poli_effect = ifelse (da$poli=="left" , -1,1)
da$id = factor(da$id)



rl = glmer (more_extreme ~acroph_condition + scale(threshold)+
              (1|threshold:id)+
              (1|id) , family = "binomial", 
            data=filter(da, poli=="left"),
            glmerControl(optimizer = "bobyqa", optCtrl = list(maxfun = 100000))) ;summary(rl)


rll = lmer (more_extreme ~acroph_condition + scale(threshold)+
              (1|threshold:id)+
              (1|id) , 
            data=filter(da, poli=="left")) ;summary(rll)

confint (rll)
r.squaredGLMM(rll)

#calcualte precent
c_rl = fixef(rl)
logit2prob(c_rl[1]) #intercept
logit2prob(c_rl[1]+c_rl[4]) # homophily
logit2prob(c_rl[1]+c_rl[2]) # acrophily
logit2prob(c_rl[1]+c_rl[3]) # complete acrophily


##conservatives 
rr = glmer (more_extreme ~acroph_condition + scale(threshold)+
              (1|threshold:id)+
              (1|id) , family = "binomial", 
            data=filter(da, poli=="right"),
            glmerControl(optimizer = "bobyqa", optCtrl = list(maxfun = 100000))) ;summary(rr)


confint.merMod(rr,method="Wald")
           
rrl = lmer (more_extreme ~acroph_condition + scale(threshold)+
              (1|threshold:id)+
              (1|id) , 
            data=filter(da, poli=="right")) ;summary(rrl)

crrl = confint(rrl)
r.squaredGLMM(rll)


c_rr = fixef(rr)
logit2prob(c_rr[1]) #intercept
logit2prob(c_rl[1]+c_rl[4]) # homophily
logit2prob(c_rl[1]+c_rl[2]) # acrophily
logit2prob(c_rl[1]+c_rl[3]) # complete acrophily


dfc <- summarySE(da, measurevar="more_extreme", groupvars=c("acroph_condition", "poli"), na.rm = T)


abs_diff_plot <- da %>%
  ggplot(aes(x=threshold, y=more_extreme, group=acroph_condition, color=acroph_condition)) +
  geom_smooth(method = "loess", se = F)+
  facet_wrap(~poli, labeller=as_labeller(label_names), ncol = 1)+
  #geom_line()+
  #geom_errorbar(aes(ymin=ci_lower, ymax=ci_upper, color=sim_condition), alpha=0.2)+
  #scale_color_manual(labels = c("Empirical", "Random"), values = c("orange", "blue"))+
  labs(x='Retweet Number', y="Mean Absolute Difference", color="Simulation Condition")+
  theme_bw();abs_diff_plot

```
```{r}
crrl
```

```{r}



dfc <- summarySE(da, measurevar="more_extreme", groupvars=c("acroph_condition", "threshold", "poli"), na.rm = T)


ggplot(dfc,aes(x=threshold, y=more_extreme ,fill = acroph_condition, colour =acroph_condition))+
    geom_errorbar(aes(ymin=more_extreme-ci, ymax=more_extreme+ci), width=.1)+
    geom_line( aes(linetype= acroph_condition, group=acroph_condition),size = .5)+
    geom_point()+
    theme_bw()+
    theme(plot.title = element_text(hjust=0.5,size = rel(1.5)),
          axis.title.y = element_text(face="bold",  size=14),
          axis.text.x  = element_text( vjust=0.5, size=18),
          axis.text.y  = element_text( vjust=0.5, size=12),
          axis.title.x = element_text( vjust=0.5, size=18)) +
    facet_wrap(~poli, ncol = 1)+
    labs(title = "title",
          x = "xtitle", 
          y = "ytitle")

```

```{r}


dfc <- summarySE(da, measurevar="more_extreme", groupvars=c("acroph_condition", "threshold", "poli"), na.rm = T) 

dfc$acroph_condition=recode_factor(dfc$acroph_condition, 
                                   peer_empirical="Empirical",
                                   peer_acroph = "Acrophily",
                                   peer_comp_acroph ="Complete Acrophily",
                                   peer_homoph = "Homophily"
                                   )

dfc$poli=recode_factor(dfc$poli,left="Liberals",
                       right = "Conservatives"
                                   )


ggplot(dfc,aes(x=threshold, y=more_extreme , fill =acroph_condition, colour=acroph_condition))+
    geom_errorbar(aes(ymin=more_extreme-ci, ymax=more_extreme+ci), width=.5, alpha =.3)+
    scale_color_manual( values = c("black", "orange", "red", "blue"))+
    #scale_fill_discrete(labels=c("Empirical", "Acrophily", "Complete Acrophily", "Homophily"))+
    #scale_color_discrete(breaks = "acroph_condition")+
    geom_line( aes(linetype= acroph_condition, group=acroph_condition),size = .5)+
    geom_point()+
    theme_bw()+
    theme(strip.text.x = element_text(size = 14),
          legend.title=element_blank(),
          plot.title = element_text(hjust=0.5,size = rel(1.5)),
          axis.title.y = element_text(face="bold",  size=14),
          axis.text.x  = element_text( vjust=0.5, size=14),
          axis.text.y  = element_text( vjust=0.5, size=12),
          axis.title.x = element_text( vjust=0.5, size=14)) +
    facet_wrap(~poli, ncol = 2)+
    labs(
          title = "",
          x = "Retweet Number", 
          y = "P(more extreme)")



ggsave('../figures/acrophily_sim_plot.jpg', width = 8, height = 7)




dfc <- summarySE(da, measurevar="more_extreme", groupvars=c("acroph_condition",  "poli"), na.rm = T)

```

```{r blmer}


test = da %>%   sample_n(50000)


rl_test = blmer (more_extreme ~acroph_condition+(1|id) , family = "binomial", filter(test, poli=="left"));summary(rl)

```

```{r}

fixef(rl)
logit2prob(fixef(rl))
```

