---
title: "Untitled"
output: html_document
---

```{r packages}
library(tidyverse)
library(glue)
```


```{r}

# Reading in coefficient data:
coef_df <- read.csv('../data/user_coef.csv')

# Reading in long-format mean absolute difference data:
abs_diff_df_long <- read.csv('../data/mean_abs_diff_long.csv') %>%
  filter(threshold <= 5)

# Reading in long-format acrophily simulation data:
acroph_df_long <- read.csv('../data/acrophily_sim_long.csv') %>%
  filter(threshold <= 5)

# Read in processed retweet network data:
d_rt <- read.csv('../data/rt_data_processed.csv')
```

# Distribution of user political ratings:
```{r}

d
d_rt %>% 
  mutate(poli_affil = ifelse(poli_affil == 'right', 'Conservatives', 'Liberals')) %>%
  ggplot(aes(x=orig_rating_ego,  color=poli_affil)) +
  geom_histogram(fill='transparent') +
  facet_wrap(~poli_affil) +
   annotate("text", x=0.22, y = -20000, label= "Moderate") + 
  annotate("text", x=1.82, y=-20000, label= "Extreme") + 
  theme_minimal() +
  theme(plot.title = element_text(hjust = 0.5, face="bold", size = 16),
        legend.position = ('none'),
        axis.title.y = element_text(face="bold",  size=14),
        axis.text.x  = element_text( vjust=0.5, size=12),
        axis.text.y  = element_text( vjust=0.5, size=12),
        axis.title.x = element_text( vjust=0.5, size=14),
        strip.text = element_text(size = 14))+
    labs(x='', y='Count',
       title='Users Political Affiliation', color = '')


ggsave('../figures/user_poli_ratings.jpg', width = 9, height = 6)
```


# Distribution of simulation coefficients

```{r}
# Get mean user coef for each political affiliation:
coef_df_means <- coef_df %>%
  dplyr::select(-userid) %>%
  group_by(poli_affil) %>%
  summarise_all(mean) %>%
  mutate(user_coef = round(user_coef, digits = 4),
         color = ifelse(poli_affil == 'right', 'red', 'blue'))

# Get means for labels:
cons_mean <- coef_df_means %>%
  filter(poli_affil == 'right') %>%
  select(user_coef)

libs_mean <- coef_df_means %>%
  filter(poli_affil == 'left') %>%
  select(user_coef)

label_names <- c('right' = glue('Conservatives (Mean = {cons_mean$user_coef})'), 'left' = glue('Liberals (Mean = {libs_mean$user_coef})'))

coef_distplot <- coef_df %>%
  ggplot(aes(x=user_coef, color=poli_affil)) +
  facet_wrap(~poli_affil, labeller=as_labeller(label_names))+
  geom_density()+
  scale_color_manual(labels = c("Liberal", "Conservative"), values = c("blue", "red"))+
  labs(x='Acrophily Coefficient', y="Density", color='Political Affiliation')+
  theme_bw()+
  geom_vline(data=coef_df_means, aes(xintercept=user_coef), linetype='dashed', color=coef_df_means$color)

ggsave('../figures/coef_distplot.jpg', width=14, height=7)

coef_distplot
```


```{r}

label_names <- c('right' = 'Conservatives', 'left' = 'Liberals')

abs_diff_plot <- abs_diff_df_long %>%
  ggplot(aes(x=threshold, y=mean_abs_diff, group=sim_condition, color=sim_condition)) +
  facet_wrap(~poli_affil, labeller=as_labeller(label_names), ncol = 1)+
  geom_line()+
  geom_errorbar(aes(ymin=ci_lower, ymax=ci_upper, color=sim_condition), alpha=0.2)+
  scale_color_manual(labels = c("Empirical", "Random"), values = c("orange", "blue"))+
  labs(x='Retweet Number', y="Mean Absolute Difference", color="Simulation Condition")+
  theme_bw();abs_diff_plot


ggsave('../figures/abs_diff_plot.jpg', width=8, height=7)

abs_diff_plot

```


```{r}

label_names <- c('right' = 'Conservatives', 'left' = 'Liberals')

acroph_plot <- acroph_df_long %>%
  ggplot(aes(x=threshold, y=prob_more_extreme, group=sim_condition, color = sim_condition)) +
  facet_wrap(~poli_affil, labeller=as_labeller(label_names))+
  geom_line()+
  geom_errorbar(aes(ymin=ci_lower, ymax=ci_upper, color=sim_condition), alpha=0.3) +
  scale_color_manual(labels = c("Pure Acrophily", "Acrophily", "Empirical", "Homophily"), values = c("red", "orange", "green", "blue"))+
  labs(x='Retweet Number', y="P(Peer More Extreme)", color="Simulation Condition")+
  theme_bw()

ggsave('../figures/acrophily_sim_plot.jpg', width = 8, height = 7)

acroph_plot
```


