---
title: "Visualization of Strategic Identity Signaling Data"
output: html_document
---



```{r}

library(ggplot2)
library(dplyr)
d <- read.csv('data/strategic_signaling_data_long.csv')
```


```{r}

label_names <- c('no' = 'Group Overall', 'yes' = 'Moderates Only')
labelsx = c("ex","ex1")
d$avg_perceived_centered = d$avg_perceived-4
left_right_plot <- d %>%
  filter(co_cross=="co") %>% 
  ggplot(aes(x=avg_perceived_centered, y=avg_sentiment))+
  geom_smooth(method='lm', se=TRUE, aes(color=poli_affil))+
  geom_point(alpha = 0.1, aes(colour = factor(poli_affil)))+
  theme_bw()+
  theme(plot.title = element_text(hjust=0.5,size = rel(1.5)),
        axis.title.y = element_text(face="bold",  size=14),
        axis.text.x  = element_text( vjust=0.5, size=18),
        axis.text.y  = element_text( vjust=0.5, size=12),
        axis.title.x = element_text( vjust=0.5, size=18)) +
  facet_wrap(~is_moderate, labeller=as_labeller(label_names), ncol=1)+
  scale_color_manual(labels = c("Liberal", "Conservative"), values = c("blue", "red"))+
  labs(x = "Perceived Copartisanship", y = "Like Tweet", color = "Political Affiliation")+
   annotate("text", x=0.15, y=1.2, label= "Moderate") + 
  annotate("text", x=2.93, y=1.2, label= "Extreme") + 
  theme_bw();left_right_plot


#ggsave('figures/avg_sentiment_avg_perceived.jpg')

left_right_plot

```

