---
title: "acrophily-twitter-SI"
author: "Jonas Paul Schöne"
date: "1/9/2023"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



```{r include = FALSE}

# Library and Data
library(sjPlot)
library(lmtest)
library(tidyverse)
library(effects)
library(lme4)
library(ggplot2)
library(extrafont)
library(Hmisc)
library(corrplot)
library(effects)
library(VGAM)
library(MuMIn)

windowsFonts(Times=windowsFont("Times New Roman"))
theme_set(theme_bw())
options(scipen = 999)

cleanup = theme(panel.grid.major = element_blank(),
              panel.grid.minor = element_blank(),
              panel.background = element_blank(),
              axis.line = element_line(colour = "black"),
              legend.key = element_rect(fill = "white"),
              text = element_text(size = 15))

df <-read.csv("user_csv/acrophily_SI_twitter.csv") %>% 
  dplyr::rename (poli = poli_affil) %>% 
  dplyr::select(-X) %>% 
  mutate(ratio_sensitive_tweets = sensitive_tweets_count / tweets_count) %>% 
  dplyr::rename(acro_coef = user_coef,
                acro_coef_weighted = user_coef_weighted)

df$poli <- as.factor(df$poli)
df$followers_log <- log(df$followers_count+1)
df$following_log <- log(df$following_count+1)
df$retweets_average_log <- log(df$retweets_average +1)
df$tweets_log <- log(df$tweets_count+1)
df$mentions_average_log <- log(df$mentions_average+1)
df$posted_sensitive_tweets <- ifelse(df$ratio_sensitive_tweets != 0, "Yes","No")

df$death_average_log <- log(df$death_average+1)
df$anger_average_log <- log(df$anger_average+1)
df$sad_average_log <- log(df$sad_average+1)
df$anx_average_log <- log(df$anx_average+1)
df$we_average_log <- log(df$we_average+1)
df$they_average_log <- log(df$they_average+1)
df$power_average_log <- log(df$power_average+1)
df$WC_average_log <- log(df$WC_average+1)
df$social_average_log <- log(df$social_average+1)
df$swear_average_log <- log(df$swear_average+1)
```

# Descriptives

```{r}
summary(df)

plot(density(df$original_sentiment_average, na.rm = TRUE))
plot(density(df$retweets_average_log))
plot(density(df$followers_log))
plot(density(df$following_log))
plot(density(df$tweets_log))
plot(density(df$mentions_average_log))
plot(density(df$poli_rating, na.rm = TRUE))
plot(density(df$acro_coef, na.rm = TRUE))

# LIWC

plot(density(df$death_average_log))
plot(density(df$anger_average_log))
plot(density(df$anx_average_log))
plot(density(df$sad_average_log))
plot(density(df$social_average_log))
plot(density(df$WC_average_log))
plot(density(df$we_average_log))
plot(density(df$they_average_log))
plot(density(df$power_average_log))
```

# Political Affiliation Strength

```{r}
r0 = lm(acro_coef ~  poli_rating, df); tab_model(r0, digits = 5, digits.p = 3)

summary(r0)

lm_plot0 <- ggplot(data = df, aes(x = poli_rating, y = acro_coef))+
  theme(plot.title = element_text(hjust = 0.5))+
  geom_smooth(method=lm,size = 1)+
  geom_point()+
  labs(y = "Acrophily Coefficient", colour = "                ", x = "Strength of Political Affiliation")+
  cleanup

lm_plot0
```


# Sentiment Original

```{r warning = FALSE }
df_f <- df %>% 
  mutate(sd_filter = scale(original_sentiment_average)) %>% 
  filter(abs(sd_filter) < 2)

r1 = lm(acro_coef ~  original_sentiment_average + scale(poli_rating) + number_of_collected_tweets, df); tab_model(r1, digits = 5, digits.p = 3, show.stat = TRUE)



summary(r1)
ee <- as.data.frame(Effect(c("original_sentiment_average"),r1,xlevels= 100))

lm_plot1 <- ggplot(data = ee, aes(x = original_sentiment_average, y = fit))+
  theme(plot.title = element_text(hjust = 0.5))+
  geom_smooth(method=lm,size = 1)+
  geom_ribbon(alpha=0.2, aes(ymin=lower,ymax=upper))+
  labs(y = "Acrophily User Coefficient", colour = "                ", x = "Average Emotion in Tweets (-1 to 1)")+
  cleanup

lm_plot1
```

# Sentiment Retweets

```{r warning = FALSE }
df_f <- df %>% 
  mutate(sd_filter = scale(retweeted_sentiment_average)) %>% 
  filter(abs(sd_filter) < 2)

r1 = lm(acro_coef ~  retweeted_sentiment_average + scale(poli_rating) + number_of_collected_tweets, df); tab_model(r1, digits = 3, digits.p = 3, show.stat = TRUE)

summary(r1)
ee <- as.data.frame(Effect(c("retweeted_sentiment_average"),r1,xlevels= 100))

lm_plot1 <- ggplot(data = ee, aes(x = retweeted_sentiment_average, y = fit))+
  theme(plot.title = element_text(hjust = 0.5))+
  geom_smooth(method=lm,size = 1)+
  geom_ribbon(alpha=0.2, aes(ymin=lower,ymax=upper))+
  labs(y = "Acrophily User Coefficient", colour = "                ", x = "Average Emotion in Retweets (-1 to 1)")+
  cleanup

lm_plot1
```

# Sentiment All COntent

```{r warning = FALSE }
df_f <- df %>% 
  mutate(sd_filter = scale(total_sentiment_average)) %>% 
  filter(abs(sd_filter) < 2)

r1 = lm(acro_coef ~  total_sentiment_average + scale(poli_rating) + number_of_collected_tweets, df); tab_model(r1, digits = 5, digits.p = 3, show.stat = TRUE)

summary(r1)
ee <- as.data.frame(Effect(c("total_sentiment_average"),r1,xlevels= 100))

lm_plot1 <- ggplot(data = ee, aes(x = total_sentiment_average, y = fit))+
  theme(plot.title = element_text(hjust = 0.5))+
  geom_smooth(method=lm,size = 1)+
  geom_ribbon(alpha=0.2, aes(ymin=lower,ymax=upper))+
  labs(y = "Acrophily User Coefficient", colour = "                ", x = "Average Emotion in all content (-1 to 1)")+
  cleanup

lm_plot1
```

# Total Number of Tweets

```{r warning = FALSE}
df_f <- df %>% 
  mutate(sd_filter = scale(tweets_log)) %>% 
  filter(abs(sd_filter) < 2)

r2 = lm(acro_coef ~  tweets_log + poli_rating + number_of_collected_tweets, df); tab_model(r2, digits = 5, digits.p = 3, show.stat = TRUE)

summary(r2)
ee <- as.data.frame(Effect(c("tweets_log"),r2,xlevels= 100))

lm_plot2 <- ggplot(data = ee, aes(x = tweets_log, y = fit))+
  theme(plot.title = element_text(hjust = 0.5))+
  geom_ribbon(alpha=0.2, aes(ymin=lower,ymax=upper))+
  geom_smooth(method=lm,size = 1)+
  labs(y = "Acrophily Coefficient", colour = "                ", x = "Total Number of Tweets")+
  cleanup

lm_plot2
```

# Number of Followers

```{r}
df_f <- df %>% 
  mutate(sd_filter = scale(followers_log)) %>% 
  filter(abs(sd_filter) < 2)

r4 = lm(acro_coef ~  followers_log + poli_rating + number_of_collected_tweets, df_f); tab_model(r4, digits = 5, digits.p = 3, show.stat = TRUE)
summary(r4)
ee <- as.data.frame(Effect(c("followers_log"),r4,xlevels= 100))

lm_plot3 <- ggplot(data = ee, aes(x = followers_log, y = fit))+
  theme(plot.title = element_text(hjust = 0.5))+
  geom_ribbon(alpha=0.2, aes(ymin=lower,ymax=upper))+
  geom_smooth(method=lm,size = 1)+
  labs(y = "Acrophily Coefficient", colour = "                ", x = "Number of Followers")+
  cleanup

lm_plot3
```

# Number of Followings

```{r}
df_f <- df %>% 
  mutate(sd_filter = scale(following_log)) %>% 
  filter(abs(sd_filter) < 2)

r5 = lm(acro_coef ~  following_log + poli_rating + number_of_collected_tweets, df_f); tab_model(r5, digits = 4, digits.p = 3, show.stat = TRUE)
summary(r5)
ee <- as.data.frame(Effect(c("following_log"),r5,xlevels= 100))

lm_plot3 <- ggplot(data = ee, aes(x = following_log, y = fit))+
  theme(plot.title = element_text(hjust = 0.5))+
  geom_ribbon(alpha=0.2, aes(ymin=lower,ymax=upper))+
  geom_smooth(method=lm,size = 1)+
  labs(y = "Acrophily Coefficient", colour = "                ", x = "Number of Followings")+
  cleanup

lm_plot3
```

# Average Number of Mentions

```{r warning = FALSE}
df_f <- df %>% 
  mutate(sd_filter = scale(mentions_average_log)) %>% 
  filter(abs(sd_filter) < 2)

r6 = lm(acro_coef ~  mentions_average_log + poli_rating + number_of_collected_tweets, df_f); tab_model(r6, digits = 3, digits.p = 3, show.stat = TRUE)
summary(r6)
ee <- as.data.frame(Effect(c("mentions_average_log"),r6,xlevels= 100))

lm_plot3 <- ggplot(data = ee, aes(x = mentions_average_log, y = fit))+
  theme(plot.title = element_text(hjust = 0.5))+
  geom_ribbon(alpha=0.2, aes(ymin=lower,ymax=upper))+
  geom_smooth(method=lm,size = 1)+
  labs(y = "Acrophily Coefficient", colour = "                ", x = "Average Number of Mentions")+
  cleanup

lm_plot3
```


## LIWC

# Average Word Count

```{r warning = FALSE}
df_f <- df %>% 
  mutate(sd_filter = scale(WC_average_log)) %>% 
  filter(abs(sd_filter) < 2)

r7 = lm(acro_coef ~  WC_average_log + poli_rating + number_of_collected_tweets, df_f); tab_model(r7, digits = 3, digits.p = 3, show.stat = TRUE)
summary(r7)
ee <- as.data.frame(Effect(c("WC_average_log"),r7,xlevels= 100))

lm_plot3 <- ggplot(data = ee, aes(x = WC_average_log, y = fit))+
  theme(plot.title = element_text(hjust = 0.5))+
  geom_ribbon(alpha=0.2, aes(ymin=lower,ymax=upper))+
  geom_smooth(method=lm,size = 1)+
  labs(y = "Acrophily Coefficient", colour = "                ", x = "Average Word Count")+
  cleanup

lm_plot3
```

# Use of They Terms

```{r warning = FALSE}
df_f <- df %>% 
  mutate(sd_filter = scale(they_average_log)) %>% 
  filter(abs(sd_filter) < 2)

r7 = lm(acro_coef ~  they_average_log + poli_rating + number_of_collected_tweets, df_f); tab_model(r7, digits = 5, digits.p = 3, show.stat = TRUE)
summary(r7)

ee <- as.data.frame(Effect(c("they_average_log"),r7,xlevels= 100))

lm_plot3 <- ggplot(data = ee, aes(x = they_average_log, y = fit))+
  theme(plot.title = element_text(hjust = 0.5))+
  geom_ribbon(alpha=0.2, aes(ymin=lower,ymax=upper))+
  geom_smooth(method=lm,size = 1)+
  labs(y = "Acrophily Coefficient", colour = "                ", x = "Average Number of They Terms")+
  cleanup

lm_plot3
```

# Use of We Terms

```{r warning = FALSE}
df_f <- df %>% 
  mutate(sd_filter = scale(we_average_log)) %>% 
  filter(abs(sd_filter) < 2)

r7 = lm(acro_coef ~  we_average_log + poli_rating + number_of_collected_tweets, df_f); tab_model(r7, digits = 4, digits.p = 3, show.stat = TRUE)
summary(r7)
ee <- as.data.frame(Effect(c("we_average_log"),r7,xlevels= 100))

lm_plot3 <- ggplot(data = ee, aes(x = we_average_log, y = fit))+
  theme(plot.title = element_text(hjust = 0.5))+
  geom_ribbon(alpha=0.2, aes(ymin=lower,ymax=upper))+
  geom_smooth(method=lm,size = 1)+
  labs(y = "Acrophily Coefficient", colour = "                ", x = "Average Number of We Terms")+
  cleanup

lm_plot3
```

# Use of Social Terms

```{r warning = FALSE}
df_f <- df %>% 
  mutate(sd_filter = scale(social_average_log)) %>% 
  filter(abs(sd_filter) < 2)

r7 = lm(acro_coef ~  social_average_log + poli_rating + number_of_collected_tweets, df_f); tab_model(r7, digits = 3, digits.p = 3, show.stat = TRUE)
summary(r7)
ee <- as.data.frame(Effect(c("social_average_log"),r7,xlevels= 100))

lm_plot3 <- ggplot(data = ee, aes(x = social_average_log, y = fit))+
  theme(plot.title = element_text(hjust = 0.5))+
  geom_ribbon(alpha=0.2, aes(ymin=lower,ymax=upper))+
  geom_smooth(method=lm,size = 1)+
  labs(y = "Acrophily Coefficient", colour = "                ", x = "Average Number of Social Terms")+
  cleanup

lm_plot3
```
