---
title: "Untitled"
output: html_document
---

```{r}
library(ggplot2)
library(dplyr)
library(glue)
library(tidyr)
```


```{r}

# Reading in coefficient data:
coef_df <- read.csv('data/user_coef.csv')

# Filtering to conservative and liberal subsets:
coef_cons <- coef_df %>% filter(affiliation == 'cons')
coef_libs <- coef_df %>% filter(affiliation == 'libs')

# Reading in long-format mean absolute difference data:
abs_diff_df_long <- read.csv('data/abs_diff_data_long.csv')

# Reading in long-format acrophily simulation data:
acroph_df_long <- read.csv('data/acroph_sim_data_long.csv')
```

# Distribution of simulation coefficients

```{r}

# Mean coefficient for conservatives and liberals (for labels):
cons_mean <- round(mean(coef_cons$coef), digits=4)
libs_mean <- round(mean(coef_libs$coef), digits=4)

# Mean coefficients for conservatives and liberals (for vertical line in plot):
coef_df_means <- coef_df %>%
  group_by(affiliation) %>%
  summarize(mean_coef = round(mean(coef), 4))

# Color variable for vertical line:
coef_df_means$color <- ifelse(coef_df_means$affiliation == 'cons', 'red', 'blue')

# Label names with means:
label_names <- c('cons' = glue('Conservatives (mean = {cons_mean})'), 'libs' = glue('Liberals (mean = {libs_mean})'))

coef_distplot <- coef_df %>%
  ggplot(aes(x=coef, color=affiliation)) +
  facet_wrap(~affiliation, labeller=as_labeller(label_names))+
  geom_density()+
  scale_color_manual(labels = c("Conservative", "Liberal"), values = c("red", "blue"))+
  labs(x='Acrophily Coefficient', y="Density")+
  theme_bw()+
  geom_vline(data=coef_df_means, aes(xintercept=mean_coef), linetype='dashed', color=coef_df_means$color);coef_distplot


#ggsave('figures/coef_distplot.jpg', width=14, height=7)

coef_distplot
```

```{r}

# Labels for facet wrap:
label_names <- c('cons' = 'Conservatives', 'libs' = 'Liberals')

mean_abs_diff_plot <- abs_diff_df_long %>%
  ggplot(aes(x=threshold, y=mean_abs_diff, group=abs_diff_condition)) +
  facet_wrap(~affiliation, labeller=as_labeller(label_names))+
  geom_line()+
  geom_ribbon(aes(ymin=mean_abs_diff-ci_moe, ymax=mean_abs_diff+ci_moe, fill=abs_diff_condition), alpha=0.3)+
  scale_fill_manual(labels = c("Empirical", "Random"), values = c("orange", "blue"))+
  labs(x='Retweet Number', y="Mean Absolute Difference", fill="Simulation Condition")+
  theme_bw();mean_abs_diff_plot


ggsave('figures/mean_abs_diff_plot.jpg', width=14, height=7)


```


```{r}




label_names <- c('cons' = 'Conservatives', 'libs' = 'Liberals')


empir <- acroph_df_long %>%
  filter(sim_condition_prob_higher=="prob_higher_empi") %>% 
  ggplot(aes(x=threshold, y=prob_higher, group=sim_condition_prob_higher)) +
  facet_wrap(~affiliation, labeller=as_labeller(label_names))+
  geom_line()+
  geom_ribbon(aes(ymin=prob_higher-ci_moe, ymax=prob_higher+ci_moe, fill=sim_condition_prob_higher), alpha=0.3)+
  scale_x_continuous(breaks=c(5,10,15,20,25,30,35,40), limits=c(5, 40)) +
  scale_fill_manual(labels = c( "Empirical", "Homophily"), values = c("green", "blue"))+
  labs(x='Retweet Number', y="P(Peer More Extreme)", fill="Simulation Condition")+
  theme_bw();empir



acroph_plot <- acroph_df_long %>%
  ggplot(aes(x=threshold, y=prob_higher, group=sim_condition_prob_higher)) +
  facet_wrap(~affiliation, labeller=as_labeller(label_names))+
  geom_line()+
  geom_ribbon(aes(ymin=prob_higher-ci_moe, ymax=prob_higher+ci_moe, fill=sim_condition_prob_higher), alpha=0.3)+
    scale_x_continuous(breaks=c(5,10,15,20,25,30,35,40), limits=c(5, 40)) +

  scale_fill_manual(labels = c("Acrophily", "Empirical", "Homophily"), values = c("red", "green", "blue"))+
  labs(x='Retweet Number', y="P(Peer More Extreme)", fill="Simulation Condition")+
  theme_bw();acroph_plot

ggsave('figures/acroph_plot.jpg', width=14, height=7)


```

