---
title: "Visualization of Strategic Identity Signaling Data"
output: html_document
---

```{r}
library(ggplot2)
library(dplyr)
```


```{r}
# Reading in data:
d <- read.csv('data/strategic_signaling_data_long.csv')

# Combining co-cross with political affiliation for facet wrap:
d$affil_co_cross <- ifelse((d$poli_affil == 'left' & d$co_cross == 'co'), 'left_co',
                            ifelse((d$poli_affil == 'right' & d$co_cross == 'co'), 'right_co',
                                   ifelse((d$poli_affil == 'left' & d$co_cross == 'cross'), 'left_cross',
                                          'right_cross')))
```


```{r}
label_names <- c('cross'='Cross-partisan', 'co'='Co-partisan', 'no'='Group Overall', 'yes'='Moderates Only')

left_right_plot_co_cross <- d %>% ggplot(aes(x=avg_perceived, y=avg_sentiment, color=poli_affil))+
  geom_smooth(method='lm', se=TRUE, aes(group=affil_co_cross))+
  facet_grid(rows=vars(co_cross), cols=vars(is_moderate), labeller=as_labeller(label_names))+
  scale_color_manual(labels = c("Liberal", "Conservative"), values = c("blue", "red"))+
  labs(x = "Averaged Perceived Copartisanship", y = "Average Sentiment", color = "Political Affiliation")+
  scale_x_continuous(breaks=c(1, 4, 7),
                     labels=c("1" = "Most Cross-partisan", "4" = "Least Co/Cross-partisan", "7" = "Most Copartisan"))+
  theme(axis.text.x = element_text(angle = 30))

ggsave('figures/avg_sentiment_avg_perceived.jpg')

left_right_plot_co_cross
```


```{r}

label_names <- c('cross'='Cross-partisan', 'co'='Co-partisan', 'no'='Group Overall', 'yes'='Moderates Only')

left_right_plot <- d %>% ggplot(aes(x=avg_perceived, y=avg_sentiment, color=poli_affil))+
  geom_smooth(method='lm', se=TRUE, aes(group=affil_co_cross))+
  facet_grid(cols=vars(is_moderate), labeller=as_labeller(label_names))+
  scale_color_manual(labels = c("Liberal", "Conservative"), values = c("blue", "red"))+
  labs(x = "Averaged Perceived Copartisanship", y = "Average Sentiment", color = "Political Affiliation")+
  scale_x_continuous(breaks=c(1, 4, 7),
                     labels=c("1" = "Most Cross-partisan", "4" = "Least Co/Cross-partisan", "7" = "Most Copartisan"))+
  theme(axis.text.x = element_text(angle = 30))

ggsave('figures/avg_sentiment_avg_perceived.jpg')

left_right_plot

```

```{r}
label_names <- c('cross'='Cross-partisan', 'co'='Co-partisan', 'no'='Group Overall', 'yes'='Moderates Only')

d_co <- d %>% filter(co_cross == 'co')

co_plot <- d_co %>% ggplot(aes(x=avg_perceived, y=avg_sentiment, color=poli_affil))+
  geom_smooth(method='lm', se=TRUE)+
  facet_wrap(~is_moderate, labeller=as_labeller(label_names), ncol=1)+
  scale_color_manual(labels = c("Liberal", "Conservative"), values = c("blue", "red"))+
  labs(x = "Averaged Perceived Copartisanship", y = "Average Sentiment", color = "Political Affiliation")+
  scale_x_continuous(breaks=c(min(d_co$avg_perceived), 7),
                     labels=c("min(d_co$avg_perceived)" = "Least Copartisan", "7" = "Most Copartisan"))+
  theme_bw()

ggsave('figures/avg_sentiment_avg_perceived_co.jpg', width=14, height=7)

co_plot
```

```{r}
label_names <- c('cross'='Cross-partisan', 'co'='Co-partisan', 'no'='Group Overall', 'yes'='Moderates Only')

d_cross <- d %>% filter(co_cross == 'co')

cross_plot <- d_cross %>% ggplot(aes(x=avg_perceived, y=avg_sentiment, color=poli_affil))+
  geom_smooth(method='lm', se=TRUE)+
  facet_wrap(~is_moderate, labeller=as_labeller(label_names), ncol=1)+
  scale_color_manual(labels = c("Liberal", "Conservative"), values = c("blue", "red"))+
  labs(x = "Averaged Perceived Copartisanship", y = "Average Sentiment", color = "Political Affiliation")+
  scale_x_continuous(breaks=c(min(d_cross$avg_perceived), max(d_cross$avg_perceived)),
                     labels=c("min(d_co$avg_perceived)" = "Least Copartisan", "max(d_cross$avg_perceived)" = "Most Copartisan"))+
  theme_bw()

ggsave('figures/avg_sentiment_avg_perceived_co.jpg', width=14, height=7)

cross_plot
```

